
DROP TABLE "MANAGER".IO;

 DROP TABLE "MANAGER"."TABLESPACE";
 DROP TABLE "MANAGER"."DATAFILE";
 DROP TABLE "MANAGER"."USERS";
 DROP TABLE "MANAGER"."SESSIONS";
DROP TABLE "MANAGER"."IO";
 DROP TABLE "MANAGER"."TABLESPACE_H";
 DROP TABLE "MANAGER"."DATAFILE_H";
 DROP TABLE "MANAGER"."USERS_H";
 DROP TABLE "MANAGER"."SESSIONS_H";


CREATE TABLE "MANAGER"."TABLESPACE" 
   (	"NAME" VARCHAR2(500 BYTE) NOT NULL, 
	"USED_SIZE" NUMBER NOT NULL, 
	"FREE_SIZE" NUMBER NOT NULL, 
	"TOTAL_SIZE" NUMBER NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL,
    CONSTRAINT TABLESPACE_PK PRIMARY KEY (NAME)
   ) ;
   
   CREATE TABLE "MANAGER"."TABLESPACE_H" 
   (	"NAME" VARCHAR2(500 BYTE) NOT NULL, 
	"USED_SIZE" NUMBER NOT NULL, 
	"FREE_SIZE" NUMBER NOT NULL, 
	"TOTAL_SIZE" NUMBER NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL,
    CONSTRAINT TABLESPACE_H_PK PRIMARY KEY (NAME,TIMESTAMP)
   ) ;
   
   CREATE TABLE "MANAGER"."DATAFILE" 
   (	"NAME_DF" VARCHAR2(500 BYTE) NOT NULL, 
	"NAME_TB" VARCHAR2(500 BYTE) NOT NULL, 
	"FILE_SIZE" NUMBER NOT NULL, 
	"USED_SIZE" NUMBER NOT NULL, 
	"FREE_SIZE" NUMBER NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL,
    CONSTRAINT DATAFILE_PK PRIMARY KEY (NAME_DF),
    CONSTRAINT FK_TABLESPACE FOREIGN KEY (NAME_TB )
        REFERENCES TABLESPACE(NAME)
   ) ;
   
  
   
   CREATE TABLE "MANAGER"."DATAFILE_H" 
   (	"NAME_DF" VARCHAR2(500 BYTE) NOT NULL, 
	"NAME_TB" VARCHAR2(500 BYTE) NOT NULL, 
	"FILE_SIZE" NUMBER NOT NULL, 
	"USED_SIZE" NUMBER NOT NULL, 
	"FREE_SIZE" NUMBER NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL,
    CONSTRAINT DATAFILE_H_PK PRIMARY KEY (NAME_DF, TIMESTAMP)
   
   ) ;
   
   CREATE TABLE "MANAGER"."USERS" 
   ("USER_ID" NUMBER NOT NULL, 
	"USERNAME" VARCHAR2(500 BYTE) NOT NULL, 
	"ACCOUNT_STATUS" VARCHAR2(500 BYTE) NOT NULL, 
	"TEMP_TB" VARCHAR2(500 BYTE) NOT NULL, 
	"CREATED" DATE NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL, 
    "NAME_TB" VARCHAR2(500 BYTE) NOT NULL, 
    CONSTRAINT USERS_PK PRIMARY KEY (USER_ID),
    CONSTRAINT FK_TABLESPACE_USERS FOREIGN KEY (NAME_TB)
        REFERENCES TABLESPACE(NAME)
   );
   
   
   
   CREATE TABLE "MANAGER"."USERS_H" 
   ("USER_ID" NUMBER NOT NULL, 
	"USERNAME" VARCHAR2(500 BYTE) NOT NULL, 
	"ACCOUNT_STATUS" VARCHAR2(500 BYTE) NOT NULL, 
	"TEMP_TB" VARCHAR2(500 BYTE) NOT NULL, 
	"CREATED" DATE NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL, 
    "NAME_TB" VARCHAR2(500 BYTE) NOT NULL, 
    CONSTRAINT USERS_H_PK PRIMARY KEY (USER_ID,TIMESTAMP)
   );
   
   CREATE TABLE "MANAGER"."SESSIONS" 
   (	"SID" VARCHAR2(500 BYTE) NOT NULL, 
	"USER_ID" NUMBER NOT NULL, 
	"USERNAME" VARCHAR2(500 BYTE) NOT NULL, 
	"SERIAL" VARCHAR2(500 BYTE) NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL, 
    CONSTRAINT SESSIONS_PK PRIMARY KEY (SID,TIMESTAMP),
    CONSTRAINT FK_SESSIONS_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS(USER_ID)
   ) ;
   
   CREATE TABLE "MANAGER"."SESSIONS_H" 
   (	"SID" VARCHAR2(500 BYTE) NOT NULL, 
	"USER_ID" NUMBER NOT NULL, 
	"USERNAME" VARCHAR2(500 BYTE) NOT NULL, 
	"SERIAL" VARCHAR2(500 BYTE) NOT NULL, 
	"TIMESTAMP" TIMESTAMP NOT NULL, 
    CONSTRAINT SESSIONS_H_PK PRIMARY KEY (SID,TIMESTAMP)
   ) ;
   
   CREATE TABLE "MANAGER"."IO" 
   (	"TIMESTAMP" TIMESTAMP  NOT NULL, 
	"WRITES" FLOAT(126)  NOT NULL, 
	"READS" FLOAT(126)  NOT NULL, 
	"FREE_MEMORY" FLOAT(126) NOT NULL,
    CONSTRAINT IO_PK PRIMARY KEY (TIMESTAMP)
   ) ;

 


----------------------------
