CREATE OR REPLACE TRIGGER add_to_TABLESPACE_H
AFTER UPDATE ON TABLESPACE FOR EACH ROW
BEGIN
    INSERT INTO TABLESPACE_H
        (NAME,USED_SIZE,FREE_SIZE,TOTAL_SIZE,TIMESTAMP)
    VALUES
        (:OLD.NAME,:OLD.USED_SIZE,:OLD.FREE_SIZE,:OLD.TOTAL_SIZE,:OLD.TIMESTAMP);   
END ;

CREATE OR REPLACE TRIGGER add_to_DATAFILE_H
AFTER UPDATE
    ON DATAFILE
FOR EACH ROW
BEGIN
    INSERT INTO DATAFILE_H
        (NAME_DF,NAME_TB,FILE_SIZE,USED_SIZE,FREE_SIZE,TIMESTAMP)
    VALUES(:OLD.NAME_DF,:OLD.NAME_TB,:OLD.FILE_SIZE,:OLD.USED_SIZE,:OLD.FREE_SIZE,:OLD.TIMESTAMP);
END;

CREATE OR REPLACE TRIGGER add_to_USERS_H
AFTER UPDATE
    ON USERS
FOR EACH ROW
BEGIN
    INSERT INTO USERS_H
        (USER_ID,USERNAME,ACCOUNT_STATUS,TEMP_TB,CREATED,TIMESTAMP,NAME_TB)
    VALUES(:OLD.USER_ID,:OLD.USERNAME,:OLD.ACCOUNT_STATUS,:OLD.TEMP_TB,:OLD.CREATED,:OLD.TIMESTAMP,:OLD.NAME_TB);
END;

CREATE OR REPLACE TRIGGER add_to_SESSIONS_H
AFTER UPDATE
    ON SESSIONS
FOR EACH ROW
BEGIN
    INSERT INTO SESSIONS_H
        (SID,USER_ID,USERNAME,SERIAL,TIMESTAMP)
    VALUES(:OLD.SID,:OLD.USER_ID,:OLD.USERNAME,:OLD.SERIAL,:OLD.TIMESTAMP);
END;